-- MySQL Script generated by MySQL Workbench
-- Tue Oct 30 00:35:49 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `Id_Usuario` INT NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(255) NOT NULL,
  `Contraseña` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`Id_Usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Roles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Roles` (
  `Id_Rol` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Rol`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Academico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Academico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Academico` (
  `Id_Academico` INT NOT NULL AUTO_INCREMENT,
  `Usuarios_idUsuarios` INT NOT NULL,
  `Nombre` VARCHAR(20) NOT NULL,
  `Nombre2` VARCHAR(20) NULL,
  `Apellido` VARCHAR(20) NOT NULL,
  `Apellido2` VARCHAR(20) NULL,
  PRIMARY KEY (`Id_Academico`),
  INDEX `fk_Academico_Usuarios1_idx` (`Usuarios_idUsuarios` ASC),
  CONSTRAINT `fk_Academico_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `mydb`.`Usuarios` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profesores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Profesores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Profesores` (
  `Id_Profesor` INT NOT NULL AUTO_INCREMENT,
  `Usuarios_idUsuarios` INT NOT NULL,
  `Matricula` INT NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Nombre2` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Apellido2` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_Profesor`),
  CONSTRAINT `fk_Profesores_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `mydb`.`Usuarios` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Alumnos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Alumnos` (
  `Id_Alumno` INT NOT NULL AUTO_INCREMENT,
  `Usuarios_idUsuarios` INT NOT NULL,
  `Matricula` INT NOT NULL,
  `Carrera` VARCHAR(40) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Nombre2` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Apellido2` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_Alumno`),
  CONSTRAINT `fk_Alumnos_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `mydb`.`Usuarios` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RolUsuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RolUsuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RolUsuarios` (
  `Id_Rol` INT NOT NULL,
  `Id_Usuario` INT NOT NULL,
  PRIMARY KEY (`Id_Rol`, `Id_Usuario`),
  INDEX `fk_Roles_has_Usuarios_Usuarios1_idx` (`Id_Usuario` ASC),
  INDEX `fk_Roles_has_Usuarios_Roles1_idx` (`Id_Rol` ASC),
  CONSTRAINT `fk_Roles_has_Usuarios_Roles1`
    FOREIGN KEY (`Id_Rol`)
    REFERENCES `mydb`.`Roles` (`Id_Rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Roles_has_Usuarios_Usuarios1`
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `mydb`.`Usuarios` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Anuncio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Anuncio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Anuncio` (
  `Id_Anuncio` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Fecha_Inicio` DATE NOT NULL,
  `Fecha_Fin` VARCHAR(45) NOT NULL,
  `Imagen` VARCHAR(100) NOT NULL,
  `Descripcion` TEXT(40) NOT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`Id_Anuncio`),
  INDEX `fk_Anuncio_Usuarios1_idx` (`Usuarios_idUsuarios` ASC),
  CONSTRAINT `fk_Anuncio_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `mydb`.`Usuarios` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tag` (
  `Id_Tag` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Tag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tag_Anuncio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tag_Anuncio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tag_Anuncio` (
  `Id_Anuncio` INT NOT NULL,
  `Id_Tag` INT NOT NULL,
  PRIMARY KEY (`Id_Anuncio`, `Id_Tag`),
  INDEX `fk_Anuncio_has_Tag_Tag1_idx` (`Id_Tag` ASC),
  INDEX `fk_Anuncio_has_Tag_Anuncio1_idx` (`Id_Anuncio` ASC),
  CONSTRAINT `fk_Anuncio_has_Tag_Anuncio1`
    FOREIGN KEY (`Id_Anuncio`)
    REFERENCES `mydb`.`Anuncio` (`Id_Anuncio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anuncio_has_Tag_Tag1`
    FOREIGN KEY (`Id_Tag`)
    REFERENCES `mydb`.`Tag` (`Id_Tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Preferencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Preferencias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Preferencias` (
  `Id_Usuario` INT NOT NULL,
  `Id_Tag` INT NOT NULL,
  PRIMARY KEY (`Id_Usuario`, `Id_Tag`),
  INDEX `fk_Usuarios_has_Tag_Tag1_idx` (`Id_Tag` ASC),
  INDEX `fk_Usuarios_has_Tag_Usuarios1_idx` (`Id_Usuario` ASC),
  CONSTRAINT `fk_Usuarios_has_Tag_Usuarios1`
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `mydb`.`Usuarios` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_has_Tag_Tag1`
    FOREIGN KEY (`Id_Tag`)
    REFERENCES `mydb`.`Tag` (`Id_Tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
